version: '3.1'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: test_db
    ports:
      - "3306:3306"
    expose:
      - '3306'

  client:
    build: crawler/
    ports:
      - "8080:8080"
    depends_on:
      - db